-- 26-3-2024 --

CREATE TABLE `banners` ( `id` INT NOT NULL AUTO_INCREMENT , `name` VARCHAR(200) NOT NULL , `image_path` TEXT NOT NULL , `created_at` DATE NOT NULL , `updated_at` DATE NULL DEFAULT NULL , PRIMARY KEY (`id`)) ENGINE = InnoDB;

ALTER TABLE `banners` ADD `status` TINYINT(1) NOT NULL DEFAULT '1' AFTER `image_path`;
ALTER TABLE `banners` CHANGE `created_at` `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP;


-- 29-3-2024 --

CREATE TABLE `banners_contents` ( `id` INT NOT NULL AUTO_INCREMENT , `image` TEXT NOT NULL , `contents` TEXT NOT NULL , `position` VARCHAR(20) NOT NULL COMMENT 'left or right' , `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP , `updated_at` DATE NULL DEFAULT NULL , PRIMARY KEY (`id`)) ENGINE = InnoDB;
CREATE TABLE `about_us` ( `id` INT NOT NULL AUTO_INCREMENT , `title` VARCHAR(200) NOT NULL , `contents` TEXT NOT NULL , `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP , `updated_at` DATE NULL DEFAULT NULL , PRIMARY KEY (`id`)) ENGINE = InnoDB;
CREATE TABLE `online_contents` ( `id` INT NOT NULL AUTO_INCREMENT , `title` VARCHAR(200) NOT NULL , `link` TEXT NOT NULL , `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP , `updated_at` DATE NULL DEFAULT NULL , PRIMARY KEY (`id`)) ENGINE = InnoDB;
ALTER TABLE `online_contents` ADD `type` VARCHAR(50) NOT NULL COMMENT 'fee, result rxam info' AFTER `link`;
ALTER TABLE `online_contents` CHANGE `type` `type` VARCHAR(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL COMMENT 'fee, result, exam';
CREATE TABLE `home_page_arcive` ( `id` INT NOT NULL AUTO_INCREMENT , `title` VARCHAR(200) NOT NULL , `image_path` TEXT NOT NULL , `status` TINYINT(1) NOT NULL DEFAULT '1' , `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP , `updated_at` DATE NULL DEFAULT NULL , PRIMARY KEY (`id`)) ENGINE = InnoDB;
CREATE TABLE `all_events` ( `id` INT NOT NULL AUTO_INCREMENT , `title` VARCHAR(200) NOT NULL , `link` TEXT NOT NULL , `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP , `updated_at` DATE NULL DEFAULT NULL , PRIMARY KEY (`id`)) ENGINE = InnoDB;
CREATE TABLE `web_settings` ( `id` INT NOT NULL AUTO_INCREMENT , `school_name` VARCHAR(200) NULL DEFAULT NULL , `address` VARCHAR(200) NULL DEFAULT NULL , `school_code` VARCHAR(100) NULL DEFAULT NULL , `logo` TEXT NULL DEFAULT NULL , `phone` VARCHAR(100) NULL DEFAULT NULL , `email` VARCHAR(50) NULL DEFAULT NULL , PRIMARY KEY (`id`)) ENGINE = InnoDB;

